services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URL=${MONGO_URL}
      - COINGECKO_API=${COINGECKO_API}
    depends_on:
      - mongo
      - redis
    networks:
      - crypto-crash-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_PROXY=http://backend:3000
    depends_on:
      - backend
    networks:
      - crypto-crash-network

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - crypto-crash-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - crypto-crash-network

volumes:
  mongo-data:

networks:
  crypto-crash-network:
    driver: bridge